'use strict';
const RS = RStartpage;
const ui = {};
let language = 'ru'; let editing = null; let selectedTag = '';
const TXT = { ru: { page:'Заметки', intro:'Ваши заметки синхронизируются между устройствами Chrome.', search:'Поиск по заметкам…', all:'Все группы', newNote:'Новая заметка', export:'Экспорт', import:'Импорт', empty:'Заметок пока нет', emptyText:'Создайте первую заметку или выделите текст на странице.', edit:'Изменить', remove:'Удалить', updated:'Изменено', created:'Создано', source:'Источник', save:'Сохранить', cancel:'Отмена', required:'Введите заголовок или содержимое.', imported:'Импортировано заметок: {count}.', invalid:'Некорректный файл заметок.', group:'Группа', newGroup:'Новая группа', groupName:'Название группы' }, en: { page:'Notes', intro:'Your notes sync between Chrome devices.', search:'Search notes…', all:'All groups', newNote:'New note', export:'Export', import:'Import', empty:'No notes yet', emptyText:'Create a note or select text on a page.', edit:'Edit', remove:'Delete', updated:'Updated', created:'Created', source:'Source', save:'Save', cancel:'Cancel', required:'Enter a title or content.', imported:'Imported notes: {count}.', invalid:'Invalid notes file.', group:'Group', newGroup:'New group', groupName:'Group name' } };
function tr(k,p={}) { return String(TXT[language]?.[k] || TXT.en[k] || k).replace(/\{(\w+)\}/g,(_,n)=>p[n] ?? ''); }
window.addEventListener('DOMContentLoaded', init);
async function init(){ cache(); bind(); RS.enableScriptActions(); const settings=await RS.loadSettings(); language=settings.language==='ru'?'ru':'en'; RS.applyPageSettings(settings,await RS.loadBackgroundImage(),document); RS.mountNavigation(ui.nav,settings,{active:'notes'}); translate(); await refresh(); const draft=await RNotes.takePendingDraft(); if(draft){ openNote(null,draft); } }
function cache(){ Object.assign(ui,{nav:document.querySelector('#appNavigation'),notice:document.querySelector('#notesNotice'),search:document.querySelector('#notesSearch'),groupFilter:document.querySelector('#notesGroupFilter'),tagBar:document.querySelector('#notesTagBar'),list:document.querySelector('#notesList'),empty:document.querySelector('#notesEmpty'),emptyTitle:document.querySelector('#notesEmptyTitle'),emptyText:document.querySelector('#notesEmptyText'),newButton:document.querySelector('#newNoteButton'),exportButton:document.querySelector('#exportNotesButton'),importButton:document.querySelector('#importNotesButton'),file:document.querySelector('#notesJsonInput'),dialog:document.querySelector('#noteDialog'),form:document.querySelector('#noteForm'),dialogTitle:document.querySelector('#noteDialogTitle'),title:document.querySelector('#noteTitle'),tags:document.querySelector('#noteTags'),group:document.querySelector('#noteGroup'),content:document.querySelector('#noteContent'),source:document.querySelector('#noteSource'),error:document.querySelector('#noteError'),save:document.querySelector('#noteSave'),cancel:document.querySelector('#noteCancel'),close:document.querySelector('#noteClose'),groupDialog:document.querySelector('#groupDialog'),groupForm:document.querySelector('#groupForm'),groupName:document.querySelector('#groupName'),groupError:document.querySelector('#groupError'),groupCancel:document.querySelector('#groupCancel'),groupClose:document.querySelector('#groupClose')}); }
function bind(){ ui.newButton.onclick=()=>openNote(); ui.exportButton.onclick=exportFile; ui.importButton.onclick=()=>ui.file.click(); ui.file.onchange=importFile; ui.search.oninput=render; ui.groupFilter.onchange=()=>ui.groupFilter.value==='__new'?openGroup():render(); ui.cancel.onclick=()=>ui.dialog.close(); ui.close.onclick=()=>ui.dialog.close(); ui.form.onsubmit=save; ui.groupCancel.onclick=()=>ui.groupDialog.close(); ui.groupClose.onclick=()=>ui.groupDialog.close(); ui.groupForm.onsubmit=saveGroup; }
function translate(){ document.documentElement.lang=language; document.title=RS.pageTitle(tr('page')); document.querySelector('#notesTitle').textContent=tr('page'); document.querySelector('#notesIntro').textContent=tr('intro'); ui.search.placeholder=tr('search'); ui.newButton.textContent=`＋ ${tr('newNote')}`; ui.exportButton.textContent=`⇩ ${tr('export')}`; ui.importButton.textContent=`⇧ ${tr('import')}`; ui.emptyTitle.textContent=tr('empty'); ui.emptyText.textContent=tr('emptyText'); ui.cancel.textContent=tr('cancel'); ui.save.textContent=tr('save'); ui.close.setAttribute('aria-label',tr('cancel')); }
async function refresh(){ const [notes,groups]=await Promise.all([RNotes.listNotes(),RNotes.listGroups()]); ui.groupFilter.innerHTML=`<option value="">${tr('all')}</option>`+groups.map(g=>`<option value="${RS.escapeHtml(g.id)}">${RS.escapeHtml(g.name)}</option>`).join('')+`<option value="__new">＋ ${tr('newGroup')}</option>`; ui.group.innerHTML=groups.map(g=>`<option value="${RS.escapeHtml(g.id)}">${RS.escapeHtml(g.name)}</option>`).join(''); const tags=[...new Set(notes.flatMap(n=>n.tags))].sort(); ui.tagBar.innerHTML=tags.map(tag=>`<button class="note-tag${selectedTag===tag?' active':''}" type="button" data-tag="${RS.escapeHtml(tag)}">#${RS.escapeHtml(tag)}</button>`).join(''); ui.tagBar.querySelectorAll('[data-tag]').forEach(b=>b.onclick=()=>{selectedTag=selectedTag===b.dataset.tag?'':b.dataset.tag;render();}); render(notes); }
async function render(cached){ const notes=cached||await RNotes.listNotes(); const query=ui.search.value.trim().toLocaleLowerCase(); const group=ui.groupFilter.value; const filtered=notes.filter(n=>(!query||`${n.title} ${n.content} ${n.tags.join(' ')} ${n.sourceUrl}`.toLocaleLowerCase().includes(query))&&(!group||n.groupId===group)&&(!selectedTag||n.tags.includes(selectedTag))); ui.list.replaceChildren(); ui.empty.hidden=filtered.length>0; const groups=await RNotes.listGroups(); const names=new Map(groups.map(g=>[g.id,g.name])); filtered.forEach(note=>{const article=document.createElement('article');article.className='note-card';article.innerHTML=`<div class="note-card-head"><div><h2>${RS.escapeHtml(note.title||'Без заголовка')}</h2><div class="note-meta">${RS.escapeHtml(names.get(note.groupId)||names.get('inbox')||'Inbox')} · ${tr('updated')} ${new Date(note.updatedAt).toLocaleString(language)}</div></div><div class="note-card-actions"><button class="button small" data-edit>${tr('edit')}</button><button class="button small danger-quiet" data-remove>${tr('remove')}</button></div></div><div class="note-tags">${note.tags.map(tag=>`<span class="note-tag">#${RS.escapeHtml(tag)}</span>`).join('')}</div><p class="note-content">${RS.escapeHtml(note.content).replace(/\n/g,'<br>')}</p>${note.sourceUrl?`<a class="note-source-link" href="${RS.escapeHtml(note.sourceUrl)}" target="_blank" rel="noopener">${RS.escapeHtml(tr('source'))}: ${RS.escapeHtml(note.sourceUrl)}</a>`:''}<div class="note-dates">${tr('created')} ${new Date(note.createdAt).toLocaleString(language)}</div>`; article.querySelector('[data-edit]').onclick=()=>openNote(note); article.querySelector('[data-remove]').onclick=async()=>{if(await RS.confirmAction({title:tr('remove'),message:note.title,confirmLabel:tr('remove')})){await RNotes.removeNote(note.id);show(tr('remove'));await refresh();}};ui.list.append(article);}); }
function openNote(note=null,draft={}){editing=note;ui.dialogTitle.textContent=note?tr('edit'):tr('newNote');ui.title.value=note?.title||draft.title||'';ui.tags.value=(note?.tags||draft.tags||[]).join(', ');ui.content.value=note?.content||draft.content||'';ui.group.value=note?.groupId||'inbox';ui.source.textContent=(note?.sourceUrl||draft.sourceUrl)?`${tr('source')}: ${note?.sourceUrl||draft.sourceUrl}`:'';ui.source.dataset.url=note?.sourceUrl||draft.sourceUrl||'';ui.error.textContent='';ui.dialog.showModal();setTimeout(()=>ui.title.focus(),0);}
async function save(event){event.preventDefault();const title=ui.title.value.trim();const content=ui.content.value.trim();if(!title&&!content){ui.error.textContent=tr('required');return;}ui.save.disabled=true;try{await RNotes.saveNote({...(editing||{}),title,tags:ui.tags.value,content,groupId:ui.group.value,sourceUrl:ui.source.dataset.url||''});ui.dialog.close();await refresh();show(tr('save'));}catch(e){ui.error.textContent=e.message||tr('required');}finally{ui.save.disabled=false;}}
function openGroup(){ui.groupName.value='';ui.groupError.textContent='';ui.groupDialog.showModal();setTimeout(()=>ui.groupName.focus(),0);}
async function saveGroup(event){event.preventDefault();const name=ui.groupName.value.trim();if(!name){ui.groupError.textContent=tr('groupName');return;}const group=await RNotes.saveGroup({name});ui.groupDialog.close();await refresh();ui.groupFilter.value=group.id;ui.group.value=group.id;}
async function exportFile(){RS.downloadJson(`rstartpage-notes-${RS.slugDate()}.json`,await RNotes.exportNotes());show(tr('export'));}
async function importFile(event){const file=event.target.files?.[0];event.target.value='';if(!file)return;try{const bundle=JSON.parse(await file.text());const count=await RNotes.importNotes(bundle,{merge:true});show(tr('imported',{count}));await refresh();}catch(e){show(tr('invalid'),true);}}
function show(message,error=false){ui.notice.textContent=message;ui.notice.classList.toggle('error',error);ui.notice.hidden=false;setTimeout(()=>ui.notice.hidden=true,4000);}
